tasks:
  - init: yarn install && yarn serve

vscode:
  extensions:
    - octref.vetur@0.24.0:wQwUWmMBrV2Y+ZN1GPaapg==

    - vscodevim.vim@1.14.5:+kFqpG8yBqdS9oQCeXaVqA==

    - ahmadawais.shades-of-purple@6.12.0:phtipGVPrS5xO6knvBtr8A==

ports:
  - port: 8080