tasks:
  - init: yarn install && yarn serve

vscode:
  extensions:
    - ahmadawais.shades-of-purple@6.11.0:KTFrDyMDGv8OYeu2xSUdeQ==
    - octref.vetur@0.24.0:wQwUWmMBrV2Y+ZN1GPaapg==

    - vscodevim.vim@1.14.5:+kFqpG8yBqdS9oQCeXaVqA==

ports:
  - port: 8080